### PR TITLE
Add comment about the dask error

### PR DESCRIPTION
**Pull request by SimonKrughoff**

### CODE REVIEW

**Review by gpdf — CHANGES_REQUESTED** [review]
Unfortunately the motd entries are severely truncated at the moment; I've requested that Matias change the page to provide more space and a general link for users to get to the full messages, but for the moment the "best practice" is to put a catchy sentence or two at the start, follow it with a link to see the rest of the messages, and then the rest of the current message text (see some of the recent messages for an example).

**Comment by SimonKrughoff** [comment]
OK.  Thanks for the tips.  Are you OK with the text?

**Comment by gpdf** [comment]
Yes, the text is fine, though if you insert the stereotyped sentence with the link, as done in some previous messages, you might end up deciding to rephrase it a bit to put the "Relax, it's OK!" punch line up front where it'll be visible in Matias' little snippet.

**Comment by SimonKrughoff** [comment]
@gpdf see changes to the wording.

**Pull request merged**
