### PR TITLE
The layout cache is not backward compatible

### PR DESCRIPTION
**Pull request by SimonKrughoff**

### CODE REVIEW

**Review by gpdf — COMMENTED** [review]
I think the first line of a MOTD, if possible, should let a user determine what sort of issue is being reported (especially because it may be all the user sees, until @mgckind gives us some more space to work with.  To me, "Layout cache needs to be refreshed" looks like it is telling the user that we're asking them to take an action.  Perhaps "JupyterLab layouts may be reset to defaults" would be a good introducer for this one?

**Comment by SimonKrughoff** [comment]
@gpdf how about now?

**Review by gpdf — APPROVED** [review]
Looks good, thank you!

**Comment by mgckind** [comment]
Thanks, I'll increase the size or think more about this and run it by you when I get back to NCSA, there are different ways we can use to increase and have a more useful MTOD display. At least, it is good to have an automatic way to display messages without going into the deployment :)

**Pull request merged**
